### ISSUE TITLE
Package makes Mono.Cecil impossible to use

### ISSUE THREAD

**Issue by yaakov-h** [TestCentric/TestCentric.Metadata#7]
I have a project that references NUnit.Engine, so it now picks up testcentric.engine.metadata as a transitive dependency.

The same project also already uses Mono.Cecil.

Updating from an older version of NUnit.Engine to a newer one results in the following build errors:

> CS0433: The type 'AssemblyDefinition' exists in both 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' and 'testcentric.engine.metadata, Version=1.7.1.0, Culture=neutral, PublicKeyToken=6fe0a02d2036aa1d'

> CS0433: The type 'ModuleAttributes' exists in both 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' and 'testcentric.engine.metadata, Version=1.7.1.0, Culture=neutral, PublicKeyToken=6fe0a02d2036aa1d'

> CS0433: The type 'TargetArchitecture' exists in both 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' and 'testcentric.engine.metadata, Version=1.7.1.0, Culture=neutral, PublicKeyToken=6fe0a02d2036aa1d'

The README says that this is based on Mono.Cecil, but can you at least rename the APIs to not conflict?

**Comment by CharliePoole** [comment]
@yaakov-h

The NUnit test engine isn't intended to be referenced by other projects, but to be accessed entirely through the nunit api assembly. That design was intended to isolate your code from situations like this. 

That said, I realize that situations can arise where you might be forced to use an actual reference to the engine itself. It will help if you can explain the nature of that situation in your use case.

Although this is a TestCentric project, it will probably be simpler to discuss how the issue arises in using the NUnit engine. You should know, however, that I left the NUnit project after the latest engine release. Consequently, you should also file an issue with the engine project (https://github.com/nunit/nunit-console) since nothing I do here will automatically fix your NUnit problem. In addition, they may want to fix this in some other way.

I will try to resolve this issue in any case, since the TestCentric engine also makes use of TestCentric.Metadata and the same problem could easily arise. As I said, some kind of description of how you use the engine and where the conflicts arise will help me to do that.

**Comment by yaakov-h** [comment]
We have a distributed test system that essentially needs two core functions:
1. Build a list of test to run on the build server
2. Run a specific test, or group of tests, one one of our many test agents.

In our older codebases we use NUnit directly, in newer ones we've switched to using VSTest, which can then invoke NUnit via the NUnit3TestAdapter package (or any other framework/engine tbh) and nicely isolates us from any test-engine-specific shenanigans like this.

From memory we started off by using nunit.engine.api but had to switch to nunit.engine due to crashes and bugs. I also seem to remember that nunit.engine.api doesn't actually include an NUnit engine, and tries to go and find one somewhere else.

With the way that the NUnit NuGet packages are structured at the moment, referencing nunit.engine brings in all of the relevant assemblies, and there doesn't seem to be a package structured such that I reference nunit.engine.api as an assembly reference and get all of the rest as content/files. That is probably the root cause of this, since the testcentric assembly is included in that directory, it isn't a transitive NuGet dependency.

Looking over the code, we have a custom ITestRunner to handle an Exception on disposal (https://github.com/nunit/nunit/issues/1656), though that seems to have been resolved so it may no longer be an issue.

We also build and initialise our own TestEngine - I don't remember why - and comments point to an `InvalidOperationException` being thrown from System.Diagnostics during application shutdown, so we have a workaround for that by nulling out `EventListener.s_EventSourceShutdownRegistered` and disposing of all event sources ourselves.

So that's our current situation in a nutshell.

It may be worth going over to the NUnit team and talking with them about restructuring the NUnit.Engine packages, but yes, other consumers including yourself could land up tripping over the same issue.

(FWIW I managed to work around this issue with an `extern alias` and a custom build target... not ideal, but it works.)

**Comment by CharliePoole** [comment]
@rprouse 

I'm thinking of changing all the `Mono.Cecil` namespaces to `TestCentric.Metadata`. Thoughts?

**Comment by rprouse** [comment]
If you mean here then yes, sounds like a good idea. We might want to do the same in the engine.

**Comment by CharliePoole** [comment]
Well, the NUnit engine actually uses the `TestCentric.Metadata` package, currently at version 1.7.1. The last release was about two years ago. Changing the namespace is breaking, so I'd probably call it version 2. Then you could update by changing some package references and `using` statements, which sounds easier than renaming methods.

BTW, I originally kept the `Mono.Cecil` namespace as a sort of homage to where the code came from. That was obviously a bit silly. :-)

**Comment by yaakov-h** [comment]
@CharliePoole that's what browser user-agents are for 😄

**Comment by CharliePoole** [comment]
@yaakov-h
This is fixed in the new 2.0.0 release available on GitHub and on nuget.org.

@rprouse @osirisTerje @jnm2 @mikkelbu @SeanKileen @stevenaw
Letting you guys know about this as issue #7 arose with an NUnit user.

I found this an easy fix for TestCentric, simply using a global replace to change `Mono.Cecil` to `TestCentric.Metadata`. Watch out for comments, which may be intentionally referring to `Mono.Cecil`.
