### ISSUE TITLE
Possible violation of Mono.Cecil license

### ISSUE THREAD

**Issue by yaakov-h** [TestCentric/TestCentric.Metadata#8]
The LICENSE file for Mono.Cecil states:

> Copyright (c) 2008 - 2015 Jb Evain
Copyright (c) 2008 - 2011 Novell, Inc.
> 
> \<snip\>
> 
> The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
>
> \<snip\>

However neither of those copyrights are presence in this repository's LICENSE file which, judging by API names and the README's own admission, appears to be a "substantial portion" of the original Cecil code.

**Comment by CharliePoole** [comment]
@yaakov-h

Those of us who distribute under the MIT license are generally doing so with full knowledge that anyone can do anything with our code, open source or commercial, and that recognition of authorship is always optional. At least that has been how I look at my work. :-)

IANAL but my understanding is that the sentence you cite from the MIT license applies to __distributing__ Mono.Cecil, not to incorporating portions of its source in a new work. In fact, according to references I have read, I could have used an entirely different license if I wished to. This is, of course, an amateur's interpretation!

What's more important to me is how @jbevain may feel about this. Jb, I have a vague memory of communicating with you about this at some point before I did it. It was initially just for my testcentric engine but I then packaged it so we could use it on NUnit. If it were a revised version of Mono.Cecil I'd have simply put my copyright on top of yours but since it's really a different program with substantially fewer features but able to run on legacy platforms that didn't seem right. In the past I've used a NOTICES file to simply recognize authorship and I'd be happy to do that here.

**Comment by jbevain** [comment]
Hello folks,

> Those of us who distribute under the MIT license are generally doing so with full knowledge that anyone can do anything with our code, open source or commercial, and that recognition of authorship is always optional. At least that has been how I look at my work. :-)

For sure :)

I'm personally happy with whatever you decide Charlie: a `NOTICES` file with the copyright holders would be nice.

**Comment by CharliePoole** [comment]
Proposed content of NOTICES.md...

`TestCentric.Metadata` is substantially based on `Mono.Cecil`, which is

```
Copyright (c) 2008 - 2015 Jb Evain
Copyright (c) 2008 - 2011 Novell, Inc.
```

We thank Jb Evain, the original author of `Mono.Cecil`, for his work.

See the README file for a description of the scope of `TestCentric.MetaData`
as compared to `Mono.Cecil`.
